const productPage =
[
    {
        id: 1,
        Name: 'Banana',
        price: '500.0',
        image: '../assets/banana.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Apple',
        price: '14.99',
        image: '../assets/apple2.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Orange',
        price: '14.99',
        image: '../assets/orange2.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Strawberry',
        price: '14.99',
        image: '../assets/strawberry.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Watermelon',
        price: '14.99',
        image: '../assets/watermelon.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 6,
        Name: 'Grapes',
        price: '14.99',
        image: '../assets/grapes.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 7,
        Name: 'Guava',
        price: '14.99',
        image: '../assets/guava.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 8,
        Name: 'Berry',
        price: '14.99',
        image: '../assets/berry.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 9,
        Name: 'Cherry',
        price: '14.99',
        image: '../assets/cherry.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 10,
        Name: 'Pineapple',
        price: '14.99',
        image: '../assets/pineapple.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 11,
        Name: 'Lemon',
        price: '14.99',
        image: '../assets/lemon.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 12,
        Name: 'Mango',
        price: '14.99',
        image: '../assets/mango.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 13,
        Name: 'Avacado Pear',
        price: '14.99',
        image: '../assets/pear.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 14,
        Name: 'Coconut',
        price: '14.99',
        image: '../assets/coconut.svg',
        cat: '',
        type: 'new',
    },
    {
        id: 15,
        Name: 'Cucumber',
        price: '14.99',
        image: '../assets/cucumber2.svg',
        cat: '',
        type: 'new',
    },
]
export default productPage